### ISSUE TITLE
hello, can you make a version of the script with a sequential search for a given range?

### ISSUE THREAD

**Issue by kozsv** [iceland2k14/Dormant5#1]

**Comment by kozsv** [comment]
hello, can you make a version of the script with a sequential search for a given range?

**Comment by iceland2k14** [comment]
Change https://github.com/iceland2k14/Dormant5/blob/5b94eac1ee5fd27fb0175c6f2f54245202f82c42/dormant5_multi.py#L112
to which ever value you want to as start Key. Rest it is already sequential
